/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppRoot {
    }
    interface TabFavs {
    }
    interface TabRandom {
    }
}
declare global {
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLTabFavsElement extends Components.TabFavs, HTMLStencilElement {
    }
    var HTMLTabFavsElement: {
        prototype: HTMLTabFavsElement;
        new (): HTMLTabFavsElement;
    };
    interface HTMLTabRandomElement extends Components.TabRandom, HTMLStencilElement {
    }
    var HTMLTabRandomElement: {
        prototype: HTMLTabRandomElement;
        new (): HTMLTabRandomElement;
    };
    interface HTMLElementTagNameMap {
        "app-root": HTMLAppRootElement;
        "tab-favs": HTMLTabFavsElement;
        "tab-random": HTMLTabRandomElement;
    }
}
declare namespace LocalJSX {
    interface AppRoot {
    }
    interface TabFavs {
    }
    interface TabRandom {
    }
    interface IntrinsicElements {
        "app-root": AppRoot;
        "tab-favs": TabFavs;
        "tab-random": TabRandom;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "tab-favs": LocalJSX.TabFavs & JSXBase.HTMLAttributes<HTMLTabFavsElement>;
            "tab-random": LocalJSX.TabRandom & JSXBase.HTMLAttributes<HTMLTabRandomElement>;
        }
    }
}
