/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppRoot {
    }
    interface QuoteListItem {
        "fetchNext": boolean;
        "id": string;
        "isFav": boolean;
        "text": string;
    }
    interface QuoteQueue {
        "items": Array<{ id: string; text: string }>;
    }
    interface TabFavs {
    }
    interface TabRandom {
    }
}
declare global {
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLQuoteListItemElement extends Components.QuoteListItem, HTMLStencilElement {
    }
    var HTMLQuoteListItemElement: {
        prototype: HTMLQuoteListItemElement;
        new (): HTMLQuoteListItemElement;
    };
    interface HTMLQuoteQueueElement extends Components.QuoteQueue, HTMLStencilElement {
    }
    var HTMLQuoteQueueElement: {
        prototype: HTMLQuoteQueueElement;
        new (): HTMLQuoteQueueElement;
    };
    interface HTMLTabFavsElement extends Components.TabFavs, HTMLStencilElement {
    }
    var HTMLTabFavsElement: {
        prototype: HTMLTabFavsElement;
        new (): HTMLTabFavsElement;
    };
    interface HTMLTabRandomElement extends Components.TabRandom, HTMLStencilElement {
    }
    var HTMLTabRandomElement: {
        prototype: HTMLTabRandomElement;
        new (): HTMLTabRandomElement;
    };
    interface HTMLElementTagNameMap {
        "app-root": HTMLAppRootElement;
        "quote-list-item": HTMLQuoteListItemElement;
        "quote-queue": HTMLQuoteQueueElement;
        "tab-favs": HTMLTabFavsElement;
        "tab-random": HTMLTabRandomElement;
    }
}
declare namespace LocalJSX {
    interface AppRoot {
    }
    interface QuoteListItem {
        "fetchNext"?: boolean;
        "id"?: string;
        "isFav"?: boolean;
        "text"?: string;
    }
    interface QuoteQueue {
        "items"?: Array<{ id: string; text: string }>;
    }
    interface TabFavs {
    }
    interface TabRandom {
    }
    interface IntrinsicElements {
        "app-root": AppRoot;
        "quote-list-item": QuoteListItem;
        "quote-queue": QuoteQueue;
        "tab-favs": TabFavs;
        "tab-random": TabRandom;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "quote-list-item": LocalJSX.QuoteListItem & JSXBase.HTMLAttributes<HTMLQuoteListItemElement>;
            "quote-queue": LocalJSX.QuoteQueue & JSXBase.HTMLAttributes<HTMLQuoteQueueElement>;
            "tab-favs": LocalJSX.TabFavs & JSXBase.HTMLAttributes<HTMLTabFavsElement>;
            "tab-random": LocalJSX.TabRandom & JSXBase.HTMLAttributes<HTMLTabRandomElement>;
        }
    }
}
